apiVersion: v1
kind: Service
metadata:
  name: wpmt-cluster-signup
spec:
  type: NodePort
  selector:
    app: wpmt-cluster-signup
  ports:
    # 'port' is the one used by the actual service 
  - port: 6601
    # 'targerPort' is the port on the Pod to which to forward traffic to 
    targetPort: 6900


--- 

# Here we have to add the Singup App deployment and specify the Docker image /that is yet to be created/ 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wpmt-cluster-signup
  labels:
    app: wpmt-cluster-signup
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wpmt-cluster-signup
  template:
    metadata:
      labels:
        app: wpmt-cluster-signup
    spec:
      containers:
      - name: wpmt-cluster-signup
        image: wpmt-cluster/signup:v0.1.1
        imagePullPolicy: Never
        env:
          - name: MYSQL_DB
            value: wpmt_cluster_db
          - name: MYSQL_USER
            value: mysql-user 
          - name: MYSQL_USER_PASSWORD
            value: mysql-pass
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
          # This defines the port on which the App can be reached outside of the container
        - containerPort: 6900

